controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_velocity_controller:
  ros__parameters:
    joints:
      - drivewhl_1_joint
      - drivewhl_2_joint
      - drivewhl_3_joint
      - drivewhl_4_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
