controller_manager:
  ros__parameters:
    update_rate: 30

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['drivewhl_fl_wheel']
    right_wheel_names: ['drivewhl_fr_wheel']
    wheel_separation: 0.5
    wheel_radius: 0.2

    use_stamped_vel: false
    publish_limited_vel: true