controller_manager:
  ros__parameters:
    update_rate: 30

    diff_cont:
      type: diff_drive_controller/DiffDriveController

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['top_left_joint', 'bottom_left_joint']
    right_wheel_names: ['top_right_joint', 'bottom_right_joint']
    wheel_separation: 0.5
    wheel_radius: 0.2

    use_stamped_vel: false